### ISSUE TITLE
Tekken has removed DRM now.

### ISSUE THREAD

**Issue by weizhen199** [KulaGGin/Tekken-7-FPS-Patcher#1]
Would you update the mod?

**Comment by KingoDenka** [comment]
I hope the dev updates this asap returning to 60 fps is giving me a headache

**Comment by weizhen199** [comment]
> turning to 60 fps is giving me a headache

Mee tooooo, it makes me vomit.

**Comment by Reshirou** [comment]
RIP

**Comment by KingoDenka** [comment]
Any update?

**Comment by Energyblast** [comment]
F

**Comment by KulaGGin** [comment]
Updated. Looks like it works.
