### ISSUE TITLE
Game does not startup

### ISSUE THREAD

**Issue by envoycookie** [KulaGGin/Tekken-7-FPS-Patcher#2]
With the latest release of the patcher the game still doesn't boot for me. But the FPS patcher in the Tekken Overlay works fine.

**Comment by KingoDenka** [comment]
Same issue here

**Comment by KulaGGin** [comment]
Oops, somehow I uploaded the old version. I updated the new release and uploaded the new version this time. Download the zip again, it should have the new version this time and let me know if it works.

**Comment by KingoDenka** [comment]
Works like a charm!

**Comment by KulaGGin** [comment]
Cool
